# a=[1,3,45,'ramanas',56]
# print(a[0:4])
# print(a[2:])
# print(a[:4])
# a=(56,'r7',234,'rty')
# print(type(a))
# b=(1,23,23,23)
# print(b)
# a=(12,34,56,65,34)
# print(a)
# b=list(a)
# b.append('saran')
# a=tuple(b)
# print(a)
# a=(12,34,45,234,345,)
# b=(1,)
# a+=b
# print(a)
# a=('saran','ZARA','tech')
# a=a*3 # to print multi lines 
# # print(a)
# a=('sar','car','var','har')
# for i in a:
#     print(i)
# for i in range(len(a)):
#     print(a)
# a=('as','frtrt','rty',123)
# b=list(a)
# b.remove(123)
# a=tuple(b)
# print(a)
